syntax = "proto3";

//添加命名空间
package MODEL_DES;

enum MESSAGE_ATTRIBUTE_TYPE 
	{ 
		BYTES_E = 0; 
		STRING_E = 1; 
		IP_E = 3; 
		BOOL_E = 4;
		INT32_E = 5;
		UINT32_E = 6;
		INT64_E = 7;
		UINT64_E = 8;
		FLOAT_E = 9;
		DOUBLE_E = 10;
		FIXED_E = 11;
		DATA_COMBOX_E = 12;  //下拉框类型
	}
	
enum MESSAGE_ATTRIBUTE_OPTION 
{ 
	REQUIRED_E = 0; //未选中
	OPTIONAL_E = 1; //选中
}
	
message Message_Combox_Item{
	string key = 1;				// 英文key值
	string desc = 2;			// 中文描述
	repeated Message_Attribute array_cmob_ele = 3;  //comb下拉框附属内容
}

message Message_Combox_Type{
	string type_key = 1;							
	string type_desc = 2; 							//实际类型值，可以填写空，或者默认某个值；
	repeated Message_Combox_Item  type_groups = 3;	//所有的下拉框的枚举，都采用Message_Combox_Type
}

message Message_Attribute {									// 参数 （键 - 值 - 最大值 - 最小值 - 描述 - 单位）
	string key = 1;
	MESSAGE_ATTRIBUTE_TYPE type = 10;	        // 与下面oneof同步使用
	oneof oneof_value {
		string string_value = 11;
		bool bool_value = 12;            //bool sting byte 类型的时候就不需要max和min
		int32 int32_value = 13;
		uint32 uint32_value = 14;
		int64 int64_value = 15;
		uint64 uint64_value = 16;
		float float_value = 17;
		double double_value = 18;
		bytes bytes_value = 19;
		string string_fix = 20;                             //真实的值，可以默认为空开始；
		Message_Combox_Type combo_type = 23; //combox下拉框类型的数据
	}

	repeated string fixedSource = 21;                                // 当type是fixed时，指定数据源，采用绝对路径形式；
	string unit = 50;									    // 单位：deg ,rad,m,cm,mm...
}


message Message_ComboAttr{                                 // 下拉选择框类型参数
    string comb_name = 1;                                       //comb本身的名称 
	string key = 2;	                                        // 选中了哪个key
	string desc = 3;                                        // 可选项描述
	repeated Message_ArrayAttr array_attr = 10;		        // 选中后需要显示的内容 - 数组
	repeated Message_ComboAttr combox_attr = 11;	        // 选中后需要显示的内容 - 下拉框
}

message Message_ArrayAttr{								// 数组类型参数
	string group_key = 3;                              // 参数组名key
    string group_name = 1;                              // 参数组名
	MESSAGE_ATTRIBUTE_OPTION option = 2;                // 是否选中
	repeated Message_Attribute attr_params = 11;		// 元素参数
}

enum COMMON_ATTR_TYPE 
	{ 
		COMBOX_E = 0; 
		ARRAY_E = 1; 
	}

//参数；
message Message_CommonAttr {							// 通用具体参数属性/功能点,具体的属性/功能点信息
    string key = 1;	                                    // 用来复制和删除此属性，没有的话不知道那些属性可被删除
	COMMON_ATTR_TYPE type = 10;							// 参数单元类型 与oneof组合使用
	oneof oneof_componentValue {		                // 具体参数的数据
		Message_ComboAttr combox_param = 11;			// 下拉选择框式的数据
		Message_ArrayAttr array_param = 12;				// 列表式的数据      
	}
	bool clone_enable = 32;								// 是否可以克隆
}

message Robot_Child_Function {						    // 子类功能
	string type = 1;                               		// 功能子类 类型 嵌入式维护枚举
	string desc	= 2;		                       		// 描述 需要展示为什么
	string key = 3;                                     // 用来复制和删除此属性，没有的话不知道那些属性可被删除(原始只能被复制，复制来得可被删除，需要用此key判断) 
	repeated Message_CommonAttr attr = 10;              // 子类 功能 属性单元
}

message Robot_Function{                                 // 功能列表的字段；一级树节点；功能树只有一级结构
	string type = 1;                                    // 功能类型
	string desc	= 2;		                       		// 描述 需要展示为什么
	repeated Robot_Child_Function child_function = 11;         // 具体的功能属性
}

message Robot_Description {
	string version = 1;							    // 模型文件版本
	repeated Robot_Function function = 12;          // 机器人功能
}